services:
  sogo-mailcow:
    entrypoint: ["sh", "-c", "echo 'SOGo disabled'; sleep infinity"]
    deploy:
      resources:
        limits:
          memory: 8m

  # Set memory limits
  clamd-mailcow:
    mem_limit: 384m
    mem_reservation: 256m
    memswap_limit: 2g
